
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             504
     no. of nonzeroes in lower triangle of a =            5867
     no. of nonzeroes in the factor l        =           17412
     ratio of nonzeroes in factor (min/max)  =          0.8430
     number of super nodes                   =              30
     maximum order of a front matrix         =              48
     maximum size of a front matrix          =            1176
     maximum size of a front trapezoid       =             876
     METIS reordering method used 
     no. of floating point ops for factor    =      4.2958D+05
     no. of floating point ops for solve     =      5.2920D+04
     ratio of flops for factor (min/max)     =          0.9568
     ratio of allocated memory (max/min)     =          1.0759
     number of positive pivots               =             504
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.022000
     time (cpu & wall) for ordering          =        0.000000        0.018000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.015625        0.009000

     no input or output performed

  Solver Memory allocated on core    0       =        0.344 MB
  Solver Memory allocated on core    1       =        0.325 MB
  Solver Memory allocated on core    2       =        0.339 MB
  Solver Memory allocated on core    3       =        0.320 MB
  Total Solver Memory allocated by all cores =        1.329 MB

